language: node_js
node_js:
  - "12.13.1"
script:
  - echo "Skipping tests"
  - npm run lint
  - npm run stylelint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUBTOKEN
  keep_history: false
  local_dir: docs
  target_branch: gh-pages
  fqdn: style.kpn.com
  email: frontend@kpn.com
  verbose: true
  on:
    branch: master
